spring:
  application:
    name: clinical-os
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:database/clinical.db
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

logging:
  level:
    root: INFO
    com.clinical: DEBUG
