spring:

  application:
    name: Society Management System

  datasource:
    url: jdbc:sqlite:data/society.db
    driver-class-name: org.sqlite.JDBC

  jpa:

    database-platform: org.hibernate.community.dialect.SQLiteDialect

    hibernate:
      ddl-auto: validate

    show-sql: true

    properties:

      hibernate:

        format_sql: true

  flyway:

    enabled: false

logging:

  level:

    root: INFO

    org.springframework: INFO

    org.hibernate.SQL: DEBUG